# Form implementation generated from reading ui file 'AddStudentInfor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1021, 480)
        Dialog.setStyleSheet("background-color: rgb(168, 192, 234);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(-90, -1, 1111, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("sms.PNG"))
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(parent=Dialog)
        self.backButton.setGeometry(QtCore.QRect(860, 440, 131, 31))
        self.backButton.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(220, 220, 220);")
        self.backButton.setObjectName("backButton")
        self.groupStudentBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupStudentBox.setGeometry(QtCore.QRect(30, 160, 961, 261))
        self.groupStudentBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(168, 192, 234);")
        self.groupStudentBox.setObjectName("groupStudentBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 111, 31))
        self.label_3.setObjectName("label_3")
        self.studentName = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentName.setGeometry(QtCore.QRect(170, 40, 241, 31))
        self.studentName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentName.setObjectName("studentName")
        self.label_4 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 111, 31))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_6.setGeometry(QtCore.QRect(30, 140, 111, 31))
        self.label_6.setObjectName("label_6")
        self.studentAddress = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentAddress.setGeometry(QtCore.QRect(170, 140, 241, 31))
        self.studentAddress.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentAddress.setObjectName("studentAddress")
        self.dateStu = QtWidgets.QDateEdit(parent=self.groupStudentBox)
        self.dateStu.setGeometry(QtCore.QRect(170, 90, 241, 31))
        self.dateStu.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.dateStu.setObjectName("dateStu")
        self.label_7 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_7.setGeometry(QtCore.QRect(30, 190, 111, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_8.setGeometry(QtCore.QRect(560, 40, 111, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_9.setGeometry(QtCore.QRect(560, 90, 111, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupStudentBox)
        self.label_10.setGeometry(QtCore.QRect(560, 140, 121, 31))
        self.label_10.setObjectName("label_10")
        self.studentClass = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentClass.setGeometry(QtCore.QRect(710, 40, 241, 31))
        self.studentClass.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentClass.setObjectName("studentClass")
        self.studentProgram = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentProgram.setGeometry(QtCore.QRect(710, 90, 241, 31))
        self.studentProgram.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentProgram.setObjectName("studentProgram")
        self.studentUni = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentUni.setGeometry(QtCore.QRect(710, 140, 241, 31))
        self.studentUni.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentUni.setObjectName("studentUni")
        self.studentMajor = QtWidgets.QLineEdit(parent=self.groupStudentBox)
        self.studentMajor.setGeometry(QtCore.QRect(170, 190, 241, 31))
        self.studentMajor.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 238, 238);")
        self.studentMajor.setObjectName("studentMajor")
        self.saveAddStudent = QtWidgets.QPushButton(parent=self.groupStudentBox)
        self.saveAddStudent.setGeometry(QtCore.QRect(820, 200, 131, 31))
        self.saveAddStudent.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(220, 220, 220);")
        self.saveAddStudent.setObjectName("saveAddStudent")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.backButton.setText(_translate("Dialog", "Back"))
        self.groupStudentBox.setTitle(_translate("Dialog", "Add Student Information"))
        self.label_3.setText(_translate("Dialog", "Student name:"))
        self.label_4.setText(_translate("Dialog", "Date of birth:"))
        self.label_6.setText(_translate("Dialog", "Address:"))
        self.label_7.setText(_translate("Dialog", "Major:"))
        self.label_8.setText(_translate("Dialog", "Class:"))
        self.label_9.setText(_translate("Dialog", "Program:"))
        self.label_10.setText(_translate("Dialog", "University years:"))
        self.saveAddStudent.setText(_translate("Dialog", "Save"))
